version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ls -la
      - echo installing "node modules"
      - npm install --legacy-peer-deps

  pre_build:
    commands:
      - echo Installing source NPM dependiencies ...
      - npm run build 
      - ls -la
  post_build:
    commands:
      - echo Deployment completed on `date`
artifacts:
    files:
      - '**/*'
    base-directory: 'build'
